FROM library/python:3.12-slim@sha256:05cda9777409a9c3ffddd94a4c476b79f0769a0b4857f0c7ed9226b6800b0d6f
RUN useradd -r -u 10001 sandbox
WORKDIR /app
COPY services/sandbox/runner.py .
USER sandbox
CMD ["python","-I","/app/runner.py"]
