FROM library/python:3.12-slim@sha256:05cda9777409a9c3ffddd94a4c476b79f0769a0b4857f0c7ed9226b6800b0d6f
WORKDIR /app
COPY services/embedding/requirements.lock .
RUN pip install --no-cache-dir uv==0.12.23 && uv pip install --system --torch-backend=cpu --require-hashes -r requirements.lock
COPY services/embedding/app.py .
CMD ["uvicorn","app:app","--host","0.0.0.0","--port","8092"]
